docker-compose down

docker rmi innovativeprojectjackdaw_producer
docker rmi innovativeprojectjackdaw_consumer
docker rmi innovativeprojectjackdaw_visualization
docker rmi innovativeprojectjackdaw_charts
