version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
    #for some machines it might be required to change kafka to their host IP adress (usually 192.168.99.100)
      KAFKA_ADVERTISED_HOST_NAME: kafka  
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
      build: ./flightdata-kafka-producer/
      volumes:
        - ./flightdata-kafka-producer/:/volume/
  schema-registry:
      image: confluent/schema-registry
      ports:
      - 8081:8081
      depends_on:
       - zookeeper
       - kafka
      environment:
      #for some machines it might be required to change schema-registry to their host IP adress (usually 192.168.99.100)
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
        SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: none
      restart: unless-stopped

# sudo docker run --net innovativeprojectjackdaw_default -d --name schema-registry -p 8081:8081 --link innovativeprojectjackdaw_zookeeper_1:zookeeper     --link wurstmeister/kafka:kafka confluent/schema-registry
