version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    # networks:
    #   - kafka-net   
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    # networks:
    #   - kafka-net
    environment:
      KAFKA_ADVERTISED_LISTENERS: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-producer:
    build: ./kafka-producer/.
    # networks:
    #   - kafka-net
    # links:
    #   - kafka
  kafka-consumer:
    build: ./kafka-consumer/.
    volumes:
        - ./kafka-consumer/:/workdir/
  #   networks:
  #     - kafka-net
  #   links:
  #     - kafka

# networks: 
#   kafka-net: 
#     driver: bridge