version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: test:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
      build: ./kafka-producer/
  consumer:
      build: ./kafka-consumer/
      volumes:
        - ./kafka-consumer/:/workdir/
  schema-registry:
      image: confluent/schema-registry
      hostname: schema-registry
      ports:
       - 8081:8081
      links:
       - zookeeper
       - kafka
      depends_on:
       - zookeeper
       - kafka
      environment:
        SCHEMA_REGISTRY_HOST_NAME: schema_registry
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
        SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: none
      restart: unless-stopped

# sudo docker run --net innovativeprojectjackdaw_default -d --name schema-registry -p 8081:8081 --link innovativeprojectjackdaw_zookeeper_1:zookeeper     --link wurstmeister/kafka:kafka confluent/schema-registry
