/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.jackdaw.avro.flights;
@SuppressWarnings("all")
/** Indicator of whether this flight was cancelled, or completed */
@org.apache.avro.specific.AvroGenerated
public enum FlightSituation {
  Realizado, Cancelado  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FlightSituation\",\"namespace\":\"com.jackdaw.avro.flights\",\"doc\":\"Indicator of whether this flight was cancelled, or completed\",\"symbols\":[\"Realizado\",\"Cancelado\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
