/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.jackdaw.avro.flights;
@SuppressWarnings("all")
/** Type of flight */
@org.apache.avro.specific.AvroGenerated
public enum FlightType {
  Internacional, Nacional, Regional  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FlightType\",\"namespace\":\"com.jackdaw.avro.flights\",\"doc\":\"Type of flight\",\"symbols\":[\"Internacional\",\"Nacional\",\"Regional\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
